### ISSUE TITLE
Form

### ISSUE THREAD

**Issue by lindacom** [allies-computing/address-lookup-php#1]
Please could you provide the code for a form which would display the results in a select field. I am new to coding and would greatly appreciate the help.

**Comment by Taelkir** [comment]
Hi @lindacom - the code in [this repo](https://github.com/allies-computing/address-lookup-javascript) should have what you need.

https://github.com/allies-computing/address-lookup-javascript

If you need any further help with Postcoder, I'd recommend sending an email over to support@alliescomputing.com
